/**
 * P31 agent crew — registry (trimtab build)
 * Expand `systemPrompt` fields from `docs/SIMPLEX-V7-COMPOSER-BRIEFING.md` / operator overlay when wiring production.
 */

import type { AgentDefinition, AgentId } from './types';

export const AGENTS: Record<AgentId, AgentDefinition> = {
  STEWARD: {
    id: 'STEWARD',
    name: 'STEWARD',
    role: 'Operations & Calendar Intelligence',
    cron: '0 6 * * *',
    triggers: ['cron', 'manual'],
    maxSpoonCost: 0,
    tools: ['get_all_deadlines', 'get_system_state', 'get_agent_outputs', 'post_agent_message'],
    outputChannels: [
      { type: 'kv', key: 'daily_briefing' },
      { type: 'agent_queue', target: 'ORACLE' },
    ],
    systemPrompt: `You are STEWARD — daily briefing, deadlines, track WCD scope. AuDHD operator; no military/naval metaphors. BONDING baseline 424/32 is P0 if regressed.`,
  },
  COUNSEL: {
    id: 'COUNSEL',
    name: 'COUNSEL',
    role: 'Legal — pro se context (court-adjacent detail in private operator docs only)',
    cron: '0 7 * * 1,3,5',
    triggers: ['cron', 'agent_handoff', 'manual'],
    maxSpoonCost: 2,
    tools: ['get_legal_events', 'log_legal_event', 'draft_document', 'get_docket_status', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'legal_events' },
      { type: 'agent_queue', target: 'SCRIBE' },
    ],
    systemPrompt: `You are COUNSEL — Georgia family court, pro se drafts, O.C.G.A.-aware. Do not publish case facts publicly; route sensitive output to SCRIBE. No naval metaphors.`,
  },
  ADVOCATE: {
    id: 'ADVOCATE',
    name: 'ADVOCATE',
    role: 'FERS / SSA forms',
    cron: '0 8 * * 1',
    triggers: ['cron', 'agent_handoff', 'manual'],
    maxSpoonCost: 1,
    tools: ['get_forms_status', 'update_form_status', 'get_deadline_countdown', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'benefits_log' },
      { type: 'kv', key: 'fers_status' },
    ],
    systemPrompt: `You are ADVOCATE — hard FERS deadline Sep 30, 2026; track SF-3112* blockers and SSA determination.`,
  },
  TREASURER: {
    id: 'TREASURER',
    name: 'TREASURER',
    role: 'Grants / Ko-fi / budget',
    cron: '0 9 * * *',
    triggers: ['cron', 'agent_handoff', 'manual'],
    maxSpoonCost: 1,
    tools: ['get_grant_status', 'update_grant_status', 'get_kofi_balance', 'get_financial_snapshot', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'financial_log' },
      { type: 'kv', key: 'financial_snapshot' },
      { type: 'agent_queue', target: 'SCHOLAR' },
    ],
    systemPrompt: `You are TREASURER — EIN 42-1888158; Awesome grant deliberation; Ko-fi vs 863 Hz target; no surprise spend without WCD.`,
  },
  FORGE: {
    id: 'FORGE',
    name: 'FORGE',
    role: 'Engineering / Workers / WCDs',
    cron: '0 */4 * * *',
    triggers: ['cron', 'http', 'agent_handoff', 'manual'],
    maxSpoonCost: 0,
    tools: ['get_worker_health', 'get_github_prs', 'get_wcd_status', 'get_test_coverage', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'engineering_log' },
      { type: 'kv', key: 'system_health' },
      { type: 'agent_queue', target: 'SCRIBE' },
    ],
    systemPrompt: `You are FORGE — worker health, BONDING 424/32 baseline, PRs, WCD drafts. SOP-03 for secrets.`,
  },
  MEDIC: {
    id: 'MEDIC',
    name: 'MEDIC',
    role: 'Medications / spoons / calcium',
    cron: '0 */6 * * *',
    triggers: ['cron', 'http', 'queue_message', 'manual'],
    maxSpoonCost: 0,
    tools: ['get_medication_status', 'log_medication', 'get_spoon_balance', 'update_spoons', 'trigger_safe_mode', 'get_calcium_gap', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'medications' },
      { type: 'd1', table: 'spoons' },
      { type: 'kv', key: 'medical_state' },
      { type: 'email', address: 'will@p31ca.org' },
    ],
    systemPrompt: `You are MEDIC — hypocalcemia risk; critical meds never skipped; spoons 12/d; escalation to ADA contact only meltdown protocols per briefing.`,
  },
  HERALD: {
    id: 'HERALD',
    name: 'HERALD',
    role: 'Comms tomograph — voltage + hostile triage',
    triggers: ['email_inbound', 'agent_handoff', 'manual'],
    maxSpoonCost: 1,
    tools: ['assess_voltage', 'log_tomograph_event', 'draft_response', 'flag_hostile_sender', 'get_spoon_balance', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'tomograph_events' },
      { type: 'kv', key: 'comms_queue' },
      { type: 'agent_queue', target: 'COUNSEL' },
    ],
    systemPrompt: `You are HERALD — hostile sender list lives in HOSTILE_SENDERS secret (never raw delivery). Route CRITICAL legal to COUNSEL queue; fawn-guard drafts.`,
  },
  SCHOLAR: {
    id: 'SCHOLAR',
    name: 'SCHOLAR',
    role: 'Research / Zenodo / grants narrative',
    cron: '0 10 * * 1',
    triggers: ['cron', 'agent_handoff', 'manual'],
    maxSpoonCost: 3,
    tools: ['get_publication_status', 'draft_grant_narrative', 'search_citations', 'prepare_zenodo_upload', 'post_agent_message'],
    outputChannels: [
      { type: 'd1', table: 'research_log' },
      { type: 'agent_queue', target: 'SCRIBE' },
      { type: 'agent_queue', target: 'TREASURER' },
    ],
    systemPrompt: `You are SCHOLAR — ORCID + Zenodo series; gated papers stay gated until operator release.`,
  },
  SCRIBE: {
    id: 'SCRIBE',
    name: 'SCRIBE',
    role: 'WCDs / ops manual / synthesis formatting',
    triggers: ['agent_handoff', 'manual'],
    maxSpoonCost: 2,
    tools: [
      'get_open_wcds',
      'create_wcd',
      'close_wcd',
      'update_ops_manual',
      'generate_session_synthesis',
      'log_manual_accommodation',
      'post_agent_message',
    ],
    outputChannels: [
      { type: 'd1', table: 'wcds' },
      { type: 'd1', table: 'accommodation_log' },
      { type: 'kv', key: 'ops_manual_version' },
    ],
    systemPrompt: `You are SCRIBE — every close needs OQE; WCD numbering; session synthesis. Accommodation log: machine rows ingest nightly (UTC) from crew telemetry; use log_manual_accommodation only when the operator reports prosthetic use the mesh did not observe (phone script, meeting outline, BONDING session, etc.).`,
  },
  SENTINEL: {
    id: 'SENTINEL',
    name: 'SENTINEL',
    role: 'Physical layer — outward bridge (HA, wearables, MQTT, mesh, haptics, TTS)',
    cron: '*/5 * * * *',
    triggers: ['cron', 'http', 'queue_message', 'manual'],
    maxSpoonCost: 0,
    tools: [
      'get_home_state',
      'set_home_scene',
      'trigger_automation',
      'get_biometric_feed',
      'update_spoons_from_biometric',
      'get_device_health',
      'push_haptic',
      'get_meshtastic_status',
      'send_tts',
      'get_presence',
      'get_sentinel_context',
      'post_agent_message',
    ],
    outputChannels: [
      { type: 'kv', key: 'home_state' },
      { type: 'kv', key: 'biometric_current' },
      { type: 'd1', table: 'device_states' },
      { type: 'd1', table: 'biometric_log' },
      { type: 'agent_queue', target: 'MEDIC' },
      { type: 'agent_queue', target: 'FORGE' },
      { type: 'agent_queue', target: 'STEWARD' },
    ],
    systemPrompt: `You are SENTINEL — the only crew member that routes *outward*: scenes, haptics, TTS, MQTT, Home Assistant automations, GadgetBridge biometric ingest. All other agents converge on D1; you bridge KV/D1 ↔ physical truth. Never put raw biometric JSON in KV; D1 biometric_log rows only — 30-day retention offline. Respect SSA/FERS medical privacy norms (health data local-first via HA until scheduled push). Use HA_TOKEN + HA_BASE_URL secrets. Node Zero POSTs hardware through /api/hardware; wearables POST /api/biometric. Prefer open hardware (e.g. Bangle.js-class) posture for future FDA-adjacent story (Node One = device-under-reg; bands are sensors). Mesh is delta — no hub.`,
  },
  ORACLE: {
    id: 'ORACLE',
    name: 'ORACLE',
    role: 'Cross-domain synthesis / Q-factor',
    cron: '0 20 * * *',
    triggers: ['cron', 'agent_handoff', 'manual'],
    maxSpoonCost: 4,
    tools: ['get_agent_outputs', 'compute_q_factor', 'detect_cross_domain_patterns', 'generate_qbd', 'post_agent_message'],
    outputChannels: [
      { type: 'kv', key: 'q_factor' },
      { type: 'd1', table: 'synthesis_log' },
      { type: 'agent_queue', target: 'SCRIBE' },
    ],
    systemPrompt: `You are ORACLE — Fisher-Escolà Q on four vertices; trimtab recommendation for tomorrow; route QBD handoff to SCRIBE.`,
  },
};

export const AGENT_IDS = Object.keys(AGENTS) as AgentId[];
